site_name: Auramana RPG
theme:
  name: material
  features:
    - navigation.tabs
    - navigation.indexes
  palette:
    primary: 'pale blue'
    accent: 'deep blue'

nav:
  - Início: indice.md
  - Auramana (D&D):
    - Raças: dnd/racas.md
    - Classes:
      - Furioso: dnd/classes/furioso.md
      - Sacerdote: dnd/classes/sacerdote.md
      - Mago: dnd/classes/mago.md
      - Guerreiro: dnd/classes/guerreiro.md
    - Origens: dnd/origens.md
    - Regras: dnd/regras.md
  - Auramana (T20):
    - Raças: t20/racas.md
    - Classes:
      - Arcanista: t20/classes/arcanista.md
      - Batedor: t20/lasses/batedor.md
      - Elementalista: t20/classes/elementalista.md
      - Guerreiro: t20/classes/guerreiro.md
      - Inspirador: t20/classes/inspirador.md
      - Inventor: t20/classes/inventor.md
      - Sacerdote: t20/classes/sacerdote.md
    - Origens: t20/origens.md
    - Regras: t20/regras.md
  - Fichas:
    - Ficha D&D: fichas/ficha-dnd.md
    - Ficha T20: fichas/ficha-t20.md
    - Ficha Pathfinder 2ed: fichas/ficha-pf2.md
  - Echo System RPG:
    - General Rules: echosystem/echo-system.md
    - Rolling Skills: echosystem/rolling-skills.md
    - Spell Skills: echosystem/spell-skills.md
    - Feat Skills: echosystem/feat-skills.md
    - Species: echosystem/classes.md
    - Classes: echosystem/species.md
    - Roles: echosystem/roles.md
   
